#line 2 "scanner.c"

#line 4 "scanner.c"

#define  YY_INT_ALIGNED short int

/* A lexical scanner generated by flex */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 5
#define YY_FLEX_SUBMINOR_VERSION 33
#if YY_FLEX_SUBMINOR_VERSION > 0
#define FLEX_BETA
#endif

/* First, we deal with  platform-specific or compiler-specific issues. */

/* begin standard C headers. */
#include <stdio.h>
#include <string.h>
#include <errno.h>
#include <stdlib.h>

/* end standard C headers. */

/* flex integer type definitions */

#ifndef FLEXINT_H
#define FLEXINT_H

/* C99 systems have <inttypes.h>. Non-C99 systems may or may not. */

#if __STDC_VERSION__ >= 199901L

/* C99 says to define __STDC_LIMIT_MACROS before including stdint.h,
 * if you want the limit (max/min) macros for int types. 
 */
#ifndef __STDC_LIMIT_MACROS
#define __STDC_LIMIT_MACROS 1
#endif

#include <inttypes.h>
typedef int8_t flex_int8_t;
typedef uint8_t flex_uint8_t;
typedef int16_t flex_int16_t;
typedef uint16_t flex_uint16_t;
typedef int32_t flex_int32_t;
typedef uint32_t flex_uint32_t;
#else
typedef signed char flex_int8_t;
typedef short int flex_int16_t;
typedef int flex_int32_t;
typedef unsigned char flex_uint8_t; 
typedef unsigned short int flex_uint16_t;
typedef unsigned int flex_uint32_t;
#endif /* ! C99 */

/* Limits of integral types. */
#ifndef INT8_MIN
#define INT8_MIN               (-128)
#endif
#ifndef INT16_MIN
#define INT16_MIN              (-32767-1)
#endif
#ifndef INT32_MIN
#define INT32_MIN              (-2147483647-1)
#endif
#ifndef INT8_MAX
#define INT8_MAX               (127)
#endif
#ifndef INT16_MAX
#define INT16_MAX              (32767)
#endif
#ifndef INT32_MAX
#define INT32_MAX              (2147483647)
#endif
#ifndef UINT8_MAX
#define UINT8_MAX              (255U)
#endif
#ifndef UINT16_MAX
#define UINT16_MAX             (65535U)
#endif
#ifndef UINT32_MAX
#define UINT32_MAX             (4294967295U)
#endif

#endif /* ! FLEXINT_H */

#ifdef __cplusplus

/* The "const" storage-class-modifier is valid. */
#define YY_USE_CONST

#else	/* ! __cplusplus */

#if __STDC__

#define YY_USE_CONST

#endif	/* __STDC__ */
#endif	/* ! __cplusplus */

#ifdef YY_USE_CONST
#define yyconst const
#else
#define yyconst
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an unsigned
 * integer for use as an array index.  If the signed char is negative,
 * we want to instead treat it as an 8-bit unsigned char, hence the
 * double cast.
 */
#define YY_SC_TO_UI(c) ((unsigned int) (unsigned char) c)

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN (yy_start) = 1 + 2 *

/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START (((yy_start) - 1) / 2)
#define YYSTATE YY_START

/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)

/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE plproxy_yyrestart(plproxy_yyin  )

#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#ifndef YY_BUF_SIZE
#define YY_BUF_SIZE 16384
#endif

/* The state buf must be large enough to hold one state per character in the main buffer.
 */
#define YY_STATE_BUF_SIZE   ((YY_BUF_SIZE + 2) * sizeof(yy_state_type))

#ifndef YY_TYPEDEF_YY_BUFFER_STATE
#define YY_TYPEDEF_YY_BUFFER_STATE
typedef struct yy_buffer_state *YY_BUFFER_STATE;
#endif

extern int plproxy_yyleng;

extern FILE *plproxy_yyin, *plproxy_yyout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2

    /* Note: We specifically omit the test for yy_rule_can_match_eol because it requires
     *       access to the local variable yy_act. Since yyless() is a macro, it would break
     *       existing scanners that call yyless() from OUTSIDE plproxy_yylex. 
     *       One obvious solution it to make yy_act a global. I tried that, and saw
     *       a 5% performance hit in a non-plproxy_yylineno scanner, because yy_act is
     *       normally declared as a register variable-- so it is not worth it.
     */
    #define  YY_LESS_LINENO(n) \
            do { \
                int yyl;\
                for ( yyl = n; yyl < plproxy_yyleng; ++yyl )\
                    if ( plproxy_yytext[yyl] == '\n' )\
                        --plproxy_yylineno;\
            }while(0)
    
/* Return all but the first "n" matched characters back to the input stream. */
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up plproxy_yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		*yy_cp = (yy_hold_char); \
		YY_RESTORE_YY_MORE_OFFSET \
		(yy_c_buf_p) = yy_cp = yy_bp + yyless_macro_arg - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up plproxy_yytext again */ \
		} \
	while ( 0 )

#define unput(c) yyunput( c, (yytext_ptr)  )

/* The following is because we cannot portably get our hands on size_t
 * (without autoconf's help, which isn't available because we want
 * flex-generated scanners to compile on their own).
 */

#ifndef YY_TYPEDEF_YY_SIZE_T
#define YY_TYPEDEF_YY_SIZE_T
typedef unsigned int yy_size_t;
#endif

#ifndef YY_STRUCT_YY_BUFFER_STATE
#define YY_STRUCT_YY_BUFFER_STATE
struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	yy_size_t yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

    int yy_bs_lineno; /**< The line count. */
    int yy_bs_column; /**< The column count. */
    
	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;

#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via plproxy_yyrestart()), so that the user can continue scanning by
	 * just pointing plproxy_yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2

	};
#endif /* !YY_STRUCT_YY_BUFFER_STATE */

/* Stack of input buffers. */
static size_t yy_buffer_stack_top = 0; /**< index of top of stack. */
static size_t yy_buffer_stack_max = 0; /**< capacity of stack. */
static YY_BUFFER_STATE * yy_buffer_stack = 0; /**< Stack as an array. */

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 *
 * Returns the top of the stack, or NULL.
 */
#define YY_CURRENT_BUFFER ( (yy_buffer_stack) \
                          ? (yy_buffer_stack)[(yy_buffer_stack_top)] \
                          : NULL)

/* Same as previous macro, but useful when we know that the buffer stack is not
 * NULL or when we need an lvalue. For internal use only.
 */
#define YY_CURRENT_BUFFER_LVALUE (yy_buffer_stack)[(yy_buffer_stack_top)]

/* yy_hold_char holds the character lost when plproxy_yytext is formed. */
static char yy_hold_char;
static int yy_n_chars;		/* number of characters read into yy_ch_buf */
int plproxy_yyleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = (char *) 0;
static int yy_init = 0;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow plproxy_yywrap()'s to do buffer switches
 * instead of setting up a fresh plproxy_yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void plproxy_yyrestart (FILE *input_file  );
void plproxy_yy_switch_to_buffer (YY_BUFFER_STATE new_buffer  );
YY_BUFFER_STATE plproxy_yy_create_buffer (FILE *file,int size  );
void plproxy_yy_delete_buffer (YY_BUFFER_STATE b  );
void plproxy_yy_flush_buffer (YY_BUFFER_STATE b  );
void plproxy_yypush_buffer_state (YY_BUFFER_STATE new_buffer  );
void plproxy_yypop_buffer_state (void );

static void plproxy_yyensure_buffer_stack (void );
static void plproxy_yy_load_buffer_state (void );
static void plproxy_yy_init_buffer (YY_BUFFER_STATE b,FILE *file  );

#define YY_FLUSH_BUFFER plproxy_yy_flush_buffer(YY_CURRENT_BUFFER )

YY_BUFFER_STATE plproxy_yy_scan_buffer (char *base,yy_size_t size  );
YY_BUFFER_STATE plproxy_yy_scan_string (yyconst char *yy_str  );
YY_BUFFER_STATE plproxy_yy_scan_bytes (yyconst char *bytes,int len  );

void *plproxy_yyalloc (yy_size_t  );
void *plproxy_yyrealloc (void *,yy_size_t  );
void plproxy_yyfree (void *  );

#define yy_new_buffer plproxy_yy_create_buffer

#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){ \
        plproxy_yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            plproxy_yy_create_buffer(plproxy_yyin,YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_is_interactive = is_interactive; \
	}

#define yy_set_bol(at_bol) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){\
        plproxy_yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            plproxy_yy_create_buffer(plproxy_yyin,YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_at_bol = at_bol; \
	}

#define YY_AT_BOL() (YY_CURRENT_BUFFER_LVALUE->yy_at_bol)

/* Begin user sect3 */

#define plproxy_yywrap(n) 1
#define YY_SKIP_YYWRAP

typedef unsigned char YY_CHAR;

FILE *plproxy_yyin = (FILE *) 0, *plproxy_yyout = (FILE *) 0;

typedef int yy_state_type;

extern int plproxy_yylineno;

int plproxy_yylineno = 1;

extern char *plproxy_yytext;
#define yytext_ptr plproxy_yytext

static yy_state_type yy_get_previous_state (void );
static yy_state_type yy_try_NUL_trans (yy_state_type current_state  );
static int yy_get_next_buffer (void );
static void yy_fatal_error (yyconst char msg[]  );

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up plproxy_yytext.
 */
#define YY_DO_BEFORE_ACTION \
	(yytext_ptr) = yy_bp; \
	plproxy_yyleng = (size_t) (yy_cp - yy_bp); \
	(yy_hold_char) = *yy_cp; \
	*yy_cp = '\0'; \
	(yy_c_buf_p) = yy_cp;

#define YY_NUM_RULES 52
#define YY_END_OF_BUFFER 53
/* This struct is not used in this scanner,
   but its presence is necessary. */
struct yy_trans_info
	{
	flex_int32_t yy_verify;
	flex_int32_t yy_nxt;
	};
static yyconst flex_int16_t yy_accept[142] =
    {   0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,   53,   20,    9,    9,
       20,   20,   20,   20,   18,   16,   16,   16,   16,   16,
       16,   51,   49,   49,   48,   31,   51,   36,   48,   48,
       47,   50,   45,   45,   32,   34,   32,   37,   39,   40,
       40,   43,   44,   23,   23,   26,   26,   28,   30,   12,
       12,   15,   15,    9,   17,    0,   19,   10,   11,   18,
        0,    8,    0,   16,   16,   16,   16,   16,    4,   16,
       16,   49,   27,   46,    0,   21,   22,   47,    0,    0,
       45,   35,   32,   32,   33,   37,   38,   40,   41,   42,

       23,   24,    0,   25,   28,   30,   29,   30,   12,   13,
        0,   14,    0,   10,    0,   16,    5,    6,   16,   16,
        3,   16,    0,   21,    0,   45,   30,   16,   16,   16,
       16,   45,   16,   16,   16,   16,   16,    7,    1,    2,
        0
    } ;

static yyconst flex_int32_t yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        1,    1,    2,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    2,    4,    5,    4,    6,    4,    4,    7,    8,
        4,    9,    4,    4,   10,   11,   12,   13,   13,   13,
       13,   13,   13,   13,   13,   13,   13,    4,   14,    4,
        4,    4,    4,    4,   17,   18,   19,   18,   20,   18,
       18,   18,   18,   18,   18,   21,   18,   22,   23,   18,
       18,   24,   25,   26,   27,   18,   18,   18,   28,   18,
        4,   15,    4,    4,   16,    1,   17,   18,   19,   18,

       20,   18,   18,   18,   18,   18,   18,   21,   18,   22,
       23,   18,   18,   24,   25,   26,   27,   18,   18,   18,
       28,   18,    4,    4,    4,    4,    1,   29,   29,   29,
       29,   29,   29,   29,   29,   29,   29,   29,   29,   29,
       29,   29,   29,   29,   29,   29,   29,   29,   29,   29,
       29,   29,   29,   29,   29,   29,   29,   29,   29,   29,
       29,   29,   29,   29,   29,   29,   29,   29,   29,   29,
       29,   29,   29,   29,   29,   29,   29,   29,   29,   29,
       29,   29,   29,   29,   29,   29,   29,   29,   29,   29,
       29,   29,   29,   29,   29,   29,   29,   29,   29,   29,

       29,   29,   29,   29,   29,   29,   29,   29,   29,   29,
       29,   29,   29,   29,   29,   29,   29,   29,   29,   29,
       29,   29,   29,   29,   29,   29,   29,   29,   29,   29,
       29,   29,   29,   29,   29,   29,   29,   29,   29,   29,
       29,   29,   29,   29,   29,   29,   29,   29,   29,   29,
       29,   29,   29,   29,   29
    } ;

static yyconst flex_int32_t yy_meta[30] =
    {   0,
        1,    2,    3,    1,    4,    5,    6,    7,    8,    1,
        9,    8,   10,    1,   11,   10,   12,   12,   12,   12,
       12,   12,   12,   12,   12,   12,   12,   12,   13
    } ;

static yyconst flex_int16_t yy_base[170] =
    {   0,
        0,    0,   29,    0,   54,   55,  484,  463,   58,   59,
       68,   69,  448,  425,   73,   80,  413,  581,   61,   65,
      395,  396,  380,  353,  344,   91,   93,   63,  332,  326,
      332,  581,   85,   88,  581,  581,   92,  581,  341,  341,
       95,  581,  107,  112,    0,  581,  117,    0,  338,    0,
        0,  336,    0,    0,    0,   88,  581,    0,  123,    0,
        0,  144,  581,  114,  329,  334,  333,    0,  581,  324,
      152,  581,  155,    0,  313,  304,  304,  308,    0,  213,
      213,  159,  581,  220,  225,    0,  581,  153,  165,  167,
      223,  581,    0,    0,  581,    0,  581,    0,  581,  581,

        0,  162,  163,  581,    0,    0,  581,  176,    0,  197,
      198,  581,  218,    0,  209,  211,    0,    0,  196,  198,
        0,  188,  167,    0,  213,  215,    0,  221,  139,  139,
      102,  225,   91,   88,   77,   55,   49,    0,    0,    0,
      581,  236,  249,  262,  275,  288,  301,  314,  326,  334,
      346,  358,  371,  384,  397,  410,  423,  436,  449,  462,
      475,  488,  500,  508,  521,  533,  545,  557,  568
    } ;

static yyconst flex_int16_t yy_def[170] =
    {   0,
      141,    1,  141,    3,  142,  142,  143,  143,  144,  144,
      145,  145,  146,  146,  147,  147,  141,  141,  141,  141,
      141,  148,  141,  141,  141,  149,  149,   27,   27,   27,
       27,  141,  141,  141,  141,  141,  150,  141,  141,  141,
      141,  141,  151,  151,  152,  141,  153,  154,  141,  155,
      155,  141,  156,  157,  157,  158,  141,  159,  141,  160,
      160,  161,  141,  141,  141,  148,  141,  162,  141,  141,
      141,  141,  163,   27,   27,   27,   27,   27,   27,   27,
       27,  141,  141,  141,  164,  165,  141,  141,  141,  166,
       44,  141,  152,  152,  141,  154,  141,  155,  141,  141,

      157,  158,  158,  141,  159,  167,  141,  141,  160,  161,
      161,  141,  148,  162,  163,  168,   27,   27,   27,   27,
       27,   27,  164,  165,  166,  169,  108,  168,   27,   27,
       27,  169,   27,   27,   27,   27,   27,   27,   27,   27,
        0,  141,  141,  141,  141,  141,  141,  141,  141,  141,
      141,  141,  141,  141,  141,  141,  141,  141,  141,  141,
      141,  141,  141,  141,  141,  141,  141,  141,  141
    } ;

static yyconst flex_int16_t yy_nxt[611] =
    {   0,
       18,   19,   20,   18,   18,   21,   22,   18,   18,   23,
       18,   24,   25,   18,   18,   18,   26,   27,   28,   27,
       27,   27,   29,   30,   31,   27,   27,   27,   18,   32,
       33,   34,   35,   36,   37,   38,   35,   35,   39,   32,
       40,   41,   42,   32,   32,   43,   43,   43,   44,   43,
       43,   43,   43,   43,   43,   43,   43,   32,   46,   46,
       51,   51,   64,   64,   52,   52,   64,   64,   47,   47,
       55,   55,   53,   53,  140,   61,   56,   56,  139,   57,
       57,   62,   61,   77,   63,   78,   82,   82,   62,   82,
       82,   63,   71,   71,   71,   71,  103,   83,   72,  104,

       72,   73,  138,   73,   84,   88,  137,   88,   89,   89,
      136,   75,   76,   89,   89,   64,   64,   90,   92,   93,
      135,   95,   90,  106,  106,  106,  106,  106,  107,  106,
      106,  106,  106,  106,  106,  106,  106,  106,  108,  108,
      108,  108,  108,  108,  108,  108,  108,  108,  108,  108,
      108,  108,  111,   71,   71,  112,  115,  115,  134,   72,
       82,   82,   73,   88,  133,   88,   89,   89,  125,  125,
      141,  103,   83,  141,  104,   90,  106,  106,  106,  106,
      106,  107,  106,  106,  106,  106,  106,  106,  127,  106,
      106,  127,  127,  127,  127,  127,  127,  127,  127,  127,

      127,  127,  127,  127,  127,  141,  111,  131,  141,  112,
      115,  115,   71,   71,  125,  125,   89,   89,   72,  130,
      129,   73,   71,   71,   67,   90,   89,   89,   72,  141,
       83,   73,   84,  122,  121,   90,   45,   45,   45,   45,
       45,   45,   45,   45,   45,   45,   45,   45,   45,   48,
       48,   48,   48,   48,   48,   48,   48,   48,   48,   48,
       48,   48,   50,   50,   50,   50,   50,   50,   50,   50,
       50,   50,   50,   50,   50,   54,   54,   54,   54,   54,
       54,   54,   54,   54,   54,   54,   54,   54,   58,   58,
       58,   58,   58,   58,   58,   58,   58,   58,   58,   58,

       58,   60,   60,   60,   60,   60,   60,   60,   60,   60,
       60,   60,   60,   60,   66,   66,   66,   66,   66,   66,
       66,   66,   66,   66,   66,   66,   66,   74,   74,  120,
      119,  118,   74,  117,   74,   74,   70,   74,   85,  113,
       67,   65,   99,   85,   97,   85,   85,   91,   91,   87,
       86,   81,   80,   79,   91,   91,   70,   91,   93,   93,
       93,   69,   93,   93,   93,   93,   93,   93,   93,   93,
       93,   94,   94,   94,   94,   94,   94,   94,   94,   94,
       94,   94,   94,   94,   96,   96,   96,   96,   96,   68,
       96,   96,   96,   96,   96,   96,   96,   98,   98,   98,

       98,   98,   67,   98,   98,   98,   98,   65,   98,   98,
      100,  100,  141,  100,  100,  100,  100,  100,  100,  100,
      100,  100,  100,  101,  101,  101,  101,  101,  101,  101,
       59,  101,  101,  101,  101,  101,  102,  102,  102,  102,
      102,  102,  102,  102,  102,  102,  102,  102,  102,  105,
      105,  105,  105,   59,  105,  105,  105,  105,  105,  105,
      105,  105,  109,  109,  109,  109,  109,  109,  109,   49,
      109,  109,  109,  109,  109,  110,  110,  110,  110,  110,
      110,  110,  110,  110,  110,  110,  110,  110,  114,  114,
       49,  114,  114,  114,  114,  114,  114,  114,  114,  114,

      114,  116,  116,  141,  141,  141,  141,  141,  141,  141,
      141,  116,  123,  141,  141,  141,  141,  123,  141,  123,
      123,  124,  124,  141,  124,  124,  124,  124,  124,  124,
      124,  124,  124,  124,  126,  126,  141,  141,  141,  141,
      141,  141,  141,  141,  126,  106,  106,  106,  106,  141,
      106,  106,  106,  106,  106,  106,  106,  106,  128,  128,
      141,  141,  141,  128,  141,  128,  128,  141,  128,  132,
      132,  141,  141,  141,  141,  141,  132,  132,  141,  132,
       17,  141,  141,  141,  141,  141,  141,  141,  141,  141,
      141,  141,  141,  141,  141,  141,  141,  141,  141,  141,

      141,  141,  141,  141,  141,  141,  141,  141,  141,  141
    } ;

static yyconst flex_int16_t yy_chk[611] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    3,
        3,    3,    3,    3,    3,    3,    3,    3,    3,    3,
        3,    3,    3,    3,    3,    3,    3,    3,    3,    3,
        3,    3,    3,    3,    3,    3,    3,    3,    5,    6,
        9,   10,   19,   19,    9,   10,   20,   20,    5,    6,
       11,   12,    9,   10,  137,   15,   11,   12,  136,   11,
       12,   15,   16,   28,   15,   28,   33,   33,   16,   34,
       34,   16,   26,   26,   27,   27,   56,   37,   26,   56,

       27,   26,  135,   27,   37,   41,  134,   41,   43,   43,
      133,   26,   26,   44,   44,   64,   64,   43,   44,   47,
      131,   47,   44,   59,   59,   59,   59,   59,   59,   59,
       59,   59,   59,   59,   59,   59,   59,   59,   59,   59,
       59,   59,   59,   59,   59,   59,   59,   59,   59,   59,
       59,   59,   62,   71,   71,   62,   73,   73,  130,   71,
       82,   82,   71,   88,  129,   88,   89,   89,   90,   90,
      102,  103,  123,  102,  103,   89,  108,  108,  108,  108,
      108,  108,  108,  108,  108,  108,  108,  108,  108,  108,
      108,  108,  108,  108,  108,  108,  108,  108,  108,  108,

      108,  108,  108,  108,  108,  110,  111,  122,  110,  111,
      115,  115,  116,  116,  125,  125,  126,  126,  116,  120,
      119,  116,  128,  128,  113,  126,  132,  132,  128,   91,
       85,  128,   84,   81,   80,  132,  142,  142,  142,  142,
      142,  142,  142,  142,  142,  142,  142,  142,  142,  143,
      143,  143,  143,  143,  143,  143,  143,  143,  143,  143,
      143,  143,  144,  144,  144,  144,  144,  144,  144,  144,
      144,  144,  144,  144,  144,  145,  145,  145,  145,  145,
      145,  145,  145,  145,  145,  145,  145,  145,  146,  146,
      146,  146,  146,  146,  146,  146,  146,  146,  146,  146,

      146,  147,  147,  147,  147,  147,  147,  147,  147,  147,
      147,  147,  147,  147,  148,  148,  148,  148,  148,  148,
      148,  148,  148,  148,  148,  148,  148,  149,  149,   78,
       77,   76,  149,   75,  149,  149,   70,  149,  150,   67,
       66,   65,   52,  150,   49,  150,  150,  151,  151,   40,
       39,   31,   30,   29,  151,  151,   25,  151,  152,  152,
      152,   24,  152,  152,  152,  152,  152,  152,  152,  152,
      152,  153,  153,  153,  153,  153,  153,  153,  153,  153,
      153,  153,  153,  153,  154,  154,  154,  154,  154,   23,
      154,  154,  154,  154,  154,  154,  154,  155,  155,  155,

      155,  155,   22,  155,  155,  155,  155,   21,  155,  155,
      156,  156,   17,  156,  156,  156,  156,  156,  156,  156,
      156,  156,  156,  157,  157,  157,  157,  157,  157,  157,
       14,  157,  157,  157,  157,  157,  158,  158,  158,  158,
      158,  158,  158,  158,  158,  158,  158,  158,  158,  159,
      159,  159,  159,   13,  159,  159,  159,  159,  159,  159,
      159,  159,  160,  160,  160,  160,  160,  160,  160,    8,
      160,  160,  160,  160,  160,  161,  161,  161,  161,  161,
      161,  161,  161,  161,  161,  161,  161,  161,  162,  162,
        7,  162,  162,  162,  162,  162,  162,  162,  162,  162,

      162,  163,  163,    0,    0,    0,    0,    0,    0,    0,
        0,  163,  164,    0,    0,    0,    0,  164,    0,  164,
      164,  165,  165,    0,  165,  165,  165,  165,  165,  165,
      165,  165,  165,  165,  166,  166,    0,    0,    0,    0,
        0,    0,    0,    0,  166,  167,  167,  167,  167,    0,
      167,  167,  167,  167,  167,  167,  167,  167,  168,  168,
        0,    0,    0,  168,    0,  168,  168,    0,  168,  169,
      169,    0,    0,    0,    0,    0,  169,  169,    0,  169,
      141,  141,  141,  141,  141,  141,  141,  141,  141,  141,
      141,  141,  141,  141,  141,  141,  141,  141,  141,  141,

      141,  141,  141,  141,  141,  141,  141,  141,  141,  141
    } ;

/* Table of booleans, true if rule could match eol. */
static yyconst flex_int32_t yy_rule_can_match_eol[53] =
    {   0,
0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 1, 0, 0, 1, 
    0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 
    1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0,     };

static yy_state_type yy_last_accepting_state;
static char *yy_last_accepting_cpos;

extern int plproxy_yy_flex_debug;
int plproxy_yy_flex_debug = 0;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char *plproxy_yytext;
#line 1 "scanner.l"
#line 2 "scanner.l"

/*
 * PL/Proxy - easy access to partitioned database.
 *
 * Copyright (c) 2006 Sven Suursoho, Skype Technologies OÜ
 * Copyright (c) 2007 Marko Kreen, Skype Technologies OÜ
 *
 * Permission to use, copy, modify, and distribute this software for any
 * purpose with or without fee is hereby granted, provided that the above
 * copyright notice and this permission notice appear in all copies.
 *
 * THE SOFTWARE IS PROVIDED "AS IS" AND THE AUTHOR DISCLAIMS ALL WARRANTIES
 * WITH REGARD TO THIS SOFTWARE INCLUDING ALL IMPLIED WARRANTIES OF
 * MERCHANTABILITY AND FITNESS. IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR
 * ANY SPECIAL, DIRECT, INDIRECT, OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES
 * WHATSOEVER RESULTING FROM LOSS OF USE, DATA OR PROFITS, WHETHER IN AN
 * ACTION OF CONTRACT, NEGLIGENCE OR OTHER TORTIOUS ACTION, ARISING OUT OF
 * OR IN CONNECTION WITH THE USE OR PERFORMANCE OF THIS SOFTWARE.
 */

#include "plproxy.h"
#include "parser.tab.h"

/* point to parser value */
#define yylval plproxy_yylval

/*
 * Allocate in CurrentMemoryContext.  That means plproxy_yylex_destroy()
 * must be called before SPI_finish().
 */
void *plproxy_yyalloc(yy_size_t len) { return palloc(len); }
void *plproxy_yyrealloc(void *ptr,yy_size_t len) { return repalloc(ptr, len); }
void plproxy_yyfree(void *ptr) { pfree(ptr); }

/* own error handling */
#define YY_FATAL_ERROR(msg) plproxy_yyerror(msg)

/* disable stdio related code */
#define YY_INPUT(buf, res, maxlen) { res = 0; }

/* shut down crappy flex warnings */
int plproxy_yyget_lineno(void);
int plproxy_yyget_leng(void);
FILE *plproxy_yyget_in(void);
FILE *plproxy_yyget_out(void);
char *plproxy_yyget_text(void);
void plproxy_yyset_lineno(int);
void plproxy_yyset_in(FILE *);
void plproxy_yyset_out(FILE *);
int plproxy_yyget_debug(void);
void plproxy_yyset_debug(int);
int plproxy_yylex_destroy(void);

/* shortcut for returning CONST */
#define RETPART do { yylval.str = plproxy_yytext; return SQLPART; } while (0)

/* dollar quoting helpers */
static void dlr_start(const char *txt);
static bool dlr_stop(const char *txt);

static const char *unquote(const char *qstr, bool std);

/* states */







/* whitespace */
/* sql ident.  include dotted parts also */
/* argument ref by val: $1 */
/* regular int value for hash spec */
/* SQL numeric value */
/*
 * Symbols that may exist in sql.   They must be matched one-by-one,
 * to avoid conflics with combos.
 *
 * Excludes: [$'";`]
 */
/* Dollar quote ID */
#line 743 "scanner.c"

#define INITIAL 0
#define sql 1
#define qident 2
#define stdq 3
#define extq 4
#define longcom 5
#define dolq 6
#define plcom 7

#ifndef YY_NO_UNISTD_H
/* Special case for "unistd.h", since it is non-ANSI. We include it way
 * down here because we want the user's section 1 to have been scanned first.
 * The user has a chance to override it with an option.
 */
#include <unistd.h>
#endif

#ifndef YY_EXTRA_TYPE
#define YY_EXTRA_TYPE void *
#endif

static int yy_init_globals (void );

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int plproxy_yywrap (void );
#else
extern int plproxy_yywrap (void );
#endif
#endif

#ifndef yytext_ptr
static void yy_flex_strncpy (char *,yyconst char *,int );
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (yyconst char * );
#endif

#ifndef YY_NO_INPUT

#ifdef __cplusplus
static int yyinput (void );
#else
static int input (void );
#endif

#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#define YY_READ_BUF_SIZE 8192
#endif

/* Copy whatever the last rule matched to the standard output. */
#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO (void) fwrite( plproxy_yytext, plproxy_yyleng, 1, plproxy_yyout )
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( YY_CURRENT_BUFFER_LVALUE->yy_is_interactive ) \
		{ \
		int c = '*'; \
		size_t n; \
		for ( n = 0; n < max_size && \
			     (c = getc( plproxy_yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( plproxy_yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else \
		{ \
		errno=0; \
		while ( (result = fread(buf, 1, max_size, plproxy_yyin))==0 && ferror(plproxy_yyin)) \
			{ \
			if( errno != EINTR) \
				{ \
				YY_FATAL_ERROR( "input in flex scanner failed" ); \
				break; \
				} \
			errno=0; \
			clearerr(plproxy_yyin); \
			} \
		}\
\

#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* end tables serialization structures and prototypes */

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL_IS_OURS 1

extern int plproxy_yylex (void);

#define YY_DECL int plproxy_yylex (void)
#endif /* !YY_DECL */

/* Code executed at the beginning of each rule, after plproxy_yytext and plproxy_yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK break;
#endif

#define YY_RULE_SETUP \
	YY_USER_ACTION

/** The main scanner function which does all the work.
 */
YY_DECL
{
	register yy_state_type yy_current_state;
	register char *yy_cp, *yy_bp;
	register int yy_act;
    
#line 110 "scanner.l"


	/* PL/Proxy language keywords */

#line 906 "scanner.c"

	if ( !(yy_init) )
		{
		(yy_init) = 1;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! (yy_start) )
			(yy_start) = 1;	/* first start state */

		if ( ! plproxy_yyin )
			plproxy_yyin = stdin;

		if ( ! plproxy_yyout )
			plproxy_yyout = stdout;

		if ( ! YY_CURRENT_BUFFER ) {
			plproxy_yyensure_buffer_stack ();
			YY_CURRENT_BUFFER_LVALUE =
				plproxy_yy_create_buffer(plproxy_yyin,YY_BUF_SIZE );
		}

		plproxy_yy_load_buffer_state( );
		}

	while ( 1 )		/* loops until end-of-file is reached */
		{
		yy_cp = (yy_c_buf_p);

		/* Support of plproxy_yytext. */
		*yy_cp = (yy_hold_char);

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = (yy_start);
yy_match:
		do
			{
			register YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)];
			if ( yy_accept[yy_current_state] )
				{
				(yy_last_accepting_state) = yy_current_state;
				(yy_last_accepting_cpos) = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 142 )
					yy_c = yy_meta[(unsigned int) yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
			++yy_cp;
			}
		while ( yy_current_state != 141 );
		yy_cp = (yy_last_accepting_cpos);
		yy_current_state = (yy_last_accepting_state);

yy_find_action:
		yy_act = yy_accept[yy_current_state];

		YY_DO_BEFORE_ACTION;

		if ( yy_act != YY_END_OF_BUFFER && yy_rule_can_match_eol[yy_act] )
			{
			int yyl;
			for ( yyl = 0; yyl < plproxy_yyleng; ++yyl )
				if ( plproxy_yytext[yyl] == '\n' )
					   
    plproxy_yylineno++;
;
			}

do_action:	/* This label is used only to access EOF actions. */

		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = (yy_hold_char);
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			goto yy_find_action;

case 1:
YY_RULE_SETUP
#line 114 "scanner.l"
{ return CLUSTER; }
	YY_BREAK
case 2:
YY_RULE_SETUP
#line 115 "scanner.l"
{ return CONNECT; }
	YY_BREAK
case 3:
YY_RULE_SETUP
#line 116 "scanner.l"
{ return RUN; }
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 117 "scanner.l"
{ return ON; }
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 118 "scanner.l"
{ return ALL; }
	YY_BREAK
case 6:
YY_RULE_SETUP
#line 119 "scanner.l"
{ return ANY; }
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 120 "scanner.l"
{ BEGIN(sql); yylval.str = plproxy_yytext; return SELECT; }
	YY_BREAK
/* function call */
case 8:
/* rule 8 can match eol */
YY_RULE_SETUP
#line 124 "scanner.l"
{ BEGIN(sql); yylval.str = plproxy_yytext; return FNCALL; }
	YY_BREAK
/* PL/Proxy language comments/whitespace */
case 9:
/* rule 9 can match eol */
YY_RULE_SETUP
#line 128 "scanner.l"
{ }
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 129 "scanner.l"
{ }
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 130 "scanner.l"
{ BEGIN(plcom); }
	YY_BREAK
case 12:
/* rule 12 can match eol */
YY_RULE_SETUP
#line 131 "scanner.l"
{ }
	YY_BREAK
case 13:
/* rule 13 can match eol */
YY_RULE_SETUP
#line 132 "scanner.l"
{ }
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 133 "scanner.l"
{ BEGIN(INITIAL); }
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 134 "scanner.l"
{ }
	YY_BREAK
/* PL/Proxy non-keyword elements */
case 16:
/* rule 16 can match eol */
YY_RULE_SETUP
#line 138 "scanner.l"
{ yylval.str = plproxy_yytext; return IDENT; }
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 139 "scanner.l"
{ yylval.str = plproxy_yytext; return IDENT; }
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 140 "scanner.l"
{ yylval.str = plproxy_yytext; return NUMBER; }
	YY_BREAK
case 19:
/* rule 19 can match eol */
YY_RULE_SETUP
#line 141 "scanner.l"
{ yylval.str = unquote(plproxy_yytext, true); return STRING; }
	YY_BREAK
/* unparsed symbol, let parser decide */
case 20:
YY_RULE_SETUP
#line 145 "scanner.l"
{ return *(plproxy_yytext); }
	YY_BREAK
/*
	 * Following is parser for SQL statements.
	 */
/* SQL line comment */
case 21:
YY_RULE_SETUP
#line 153 "scanner.l"
{ /* \n will be parsed as whitespace */ }
	YY_BREAK
/* C comment, parse it as whitespace */
case 22:
YY_RULE_SETUP
#line 157 "scanner.l"
{ BEGIN(longcom); }
	YY_BREAK
case 23:
/* rule 23 can match eol */
YY_RULE_SETUP
#line 158 "scanner.l"
{ }
	YY_BREAK
case 24:
/* rule 24 can match eol */
YY_RULE_SETUP
#line 159 "scanner.l"
{ }
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 160 "scanner.l"
{ BEGIN(sql); yylval.str = " "; return SQLPART; }
	YY_BREAK
case 26:
YY_RULE_SETUP
#line 161 "scanner.l"
{ }
	YY_BREAK
/* Dollar quoted string */
case 27:
YY_RULE_SETUP
#line 165 "scanner.l"
{ BEGIN(dolq); dlr_start(plproxy_yytext); RETPART; }
	YY_BREAK
case 28:
/* rule 28 can match eol */
YY_RULE_SETUP
#line 166 "scanner.l"
{ RETPART; }
	YY_BREAK
case 29:
YY_RULE_SETUP
#line 167 "scanner.l"
{ if (dlr_stop(plproxy_yytext)) { BEGIN(sql); RETPART; }
			  /* if wrong one, report only 1 char */
			  else { yyless(1); RETPART; } }
	YY_BREAK
case 30:
/* rule 30 can match eol */
YY_RULE_SETUP
#line 170 "scanner.l"
{ RETPART; }
	YY_BREAK
/* quoted indentifier */
case 31:
YY_RULE_SETUP
#line 174 "scanner.l"
{ BEGIN(qident); RETPART; }
	YY_BREAK
case 32:
/* rule 32 can match eol */
YY_RULE_SETUP
#line 175 "scanner.l"
{ RETPART; }
	YY_BREAK
case 33:
YY_RULE_SETUP
#line 176 "scanner.l"
{ RETPART; }
	YY_BREAK
case 34:
YY_RULE_SETUP
#line 177 "scanner.l"
{ BEGIN(sql); RETPART; }
	YY_BREAK
/* quoted string start */
case 35:
YY_RULE_SETUP
#line 181 "scanner.l"
{ BEGIN(extq); RETPART; }
	YY_BREAK
case 36:
YY_RULE_SETUP
#line 182 "scanner.l"
{ if (standard_conforming_strings)
			    BEGIN(stdq); else BEGIN(extq);
			  RETPART; }
	YY_BREAK
/* SQL standard quoted string body */
case 37:
/* rule 37 can match eol */
YY_RULE_SETUP
#line 188 "scanner.l"
{ RETPART; }
	YY_BREAK
case 38:
YY_RULE_SETUP
#line 189 "scanner.l"
{ RETPART; }
	YY_BREAK
case 39:
YY_RULE_SETUP
#line 190 "scanner.l"
{ BEGIN(sql); RETPART; }
	YY_BREAK
/* extended quoted string body */
case 40:
/* rule 40 can match eol */
YY_RULE_SETUP
#line 194 "scanner.l"
{ RETPART; }
	YY_BREAK
case 41:
YY_RULE_SETUP
#line 195 "scanner.l"
{ RETPART; }
	YY_BREAK
case 42:
YY_RULE_SETUP
#line 196 "scanner.l"
{ RETPART; }
	YY_BREAK
case 43:
YY_RULE_SETUP
#line 197 "scanner.l"
{ BEGIN(sql); RETPART; }
	YY_BREAK
case 44:
YY_RULE_SETUP
#line 198 "scanner.l"
{ RETPART; }
	YY_BREAK
/* SQL identifier */
case 45:
/* rule 45 can match eol */
YY_RULE_SETUP
#line 202 "scanner.l"
{ yylval.str = plproxy_yytext; return SQLIDENT; }
	YY_BREAK
/* $x argument reference */
case 46:
YY_RULE_SETUP
#line 206 "scanner.l"
{ yylval.str = plproxy_yytext; return SQLIDENT; }
	YY_BREAK
/* SQL number */
case 47:
YY_RULE_SETUP
#line 210 "scanner.l"
{ RETPART; }
	YY_BREAK
/* SQL symbol, parse them one-by-one */
case 48:
YY_RULE_SETUP
#line 214 "scanner.l"
{ RETPART; }
	YY_BREAK
/* compress whitespace to singe ' ' */
case 49:
/* rule 49 can match eol */
YY_RULE_SETUP
#line 218 "scanner.l"
{ yylval.str = " "; return SQLPART; }
	YY_BREAK
/* SQL statement end */
case 50:
YY_RULE_SETUP
#line 222 "scanner.l"
{ BEGIN(INITIAL); return *(plproxy_yytext); }
	YY_BREAK
/* unparsed symbol, let the parser error out */
case 51:
YY_RULE_SETUP
#line 226 "scanner.l"
{ return *(plproxy_yytext); }
	YY_BREAK
case 52:
YY_RULE_SETUP
#line 228 "scanner.l"
YY_FATAL_ERROR( "flex scanner jammed" );
	YY_BREAK
#line 1295 "scanner.c"
case YY_STATE_EOF(INITIAL):
case YY_STATE_EOF(sql):
case YY_STATE_EOF(qident):
case YY_STATE_EOF(stdq):
case YY_STATE_EOF(extq):
case YY_STATE_EOF(longcom):
case YY_STATE_EOF(dolq):
case YY_STATE_EOF(plcom):
	yyterminate();

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - (yytext_ptr)) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = (yy_hold_char);
		YY_RESTORE_YY_MORE_OFFSET

		if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed plproxy_yyin at a new source and called
			 * plproxy_yylex().  If so, then we have to assure
			 * consistency between YY_CURRENT_BUFFER and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
			YY_CURRENT_BUFFER_LVALUE->yy_input_file = plproxy_yyin;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( (yy_c_buf_p) <= &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			(yy_c_buf_p) = (yytext_ptr) + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state(  );

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = (yytext_ptr) + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++(yy_c_buf_p);
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = (yy_last_accepting_cpos);
				yy_current_state = (yy_last_accepting_state);
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer(  ) )
			{
			case EOB_ACT_END_OF_FILE:
				{
				(yy_did_buffer_switch_on_eof) = 0;

				if ( plproxy_yywrap( ) )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * plproxy_yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					(yy_c_buf_p) = (yytext_ptr) + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				(yy_c_buf_p) =
					(yytext_ptr) + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				(yy_c_buf_p) =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)];

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
} /* end of plproxy_yylex */

/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */
static int yy_get_next_buffer (void)
{
    	register char *dest = YY_CURRENT_BUFFER_LVALUE->yy_ch_buf;
	register char *source = (yytext_ptr);
	register int number_to_move, i;
	int ret_val;

	if ( (yy_c_buf_p) > &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( YY_CURRENT_BUFFER_LVALUE->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( (yy_c_buf_p) - (yytext_ptr) - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) ((yy_c_buf_p) - (yytext_ptr)) - 1;

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars) = 0;

	else
		{
			int num_to_read =
			YY_CURRENT_BUFFER_LVALUE->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = YY_CURRENT_BUFFER;

			int yy_c_buf_p_offset =
				(int) ((yy_c_buf_p) - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				int new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					plproxy_yyrealloc((void *) b->yy_ch_buf,b->yy_buf_size + 2  );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = 0;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			(yy_c_buf_p) = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = YY_CURRENT_BUFFER_LVALUE->yy_buf_size -
						number_to_move - 1;

			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move]),
			(yy_n_chars), num_to_read );

		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	if ( (yy_n_chars) == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			plproxy_yyrestart(plproxy_yyin  );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	(yy_n_chars) += number_to_move;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] = YY_END_OF_BUFFER_CHAR;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] = YY_END_OF_BUFFER_CHAR;

	(yytext_ptr) = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[0];

	return ret_val;
}

/* yy_get_previous_state - get the state just before the EOB char was reached */

    static yy_state_type yy_get_previous_state (void)
{
	register yy_state_type yy_current_state;
	register char *yy_cp;
    
	yy_current_state = (yy_start);

	for ( yy_cp = (yytext_ptr) + YY_MORE_ADJ; yy_cp < (yy_c_buf_p); ++yy_cp )
		{
		register YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			(yy_last_accepting_state) = yy_current_state;
			(yy_last_accepting_cpos) = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 142 )
				yy_c = yy_meta[(unsigned int) yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
		}

	return yy_current_state;
}

/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */
    static yy_state_type yy_try_NUL_trans  (yy_state_type yy_current_state )
{
	register int yy_is_jam;
    	register char *yy_cp = (yy_c_buf_p);

	register YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		(yy_last_accepting_state) = yy_current_state;
		(yy_last_accepting_cpos) = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 142 )
			yy_c = yy_meta[(unsigned int) yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
	yy_is_jam = (yy_current_state == 141);

	return yy_is_jam ? 0 : yy_current_state;
}

#ifndef YY_NO_INPUT
#ifdef __cplusplus
    static int yyinput (void)
#else
    static int input  (void)
#endif

{
	int c;
    
	*(yy_c_buf_p) = (yy_hold_char);

	if ( *(yy_c_buf_p) == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( (yy_c_buf_p) < &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			/* This was really a NUL. */
			*(yy_c_buf_p) = '\0';

		else
			{ /* need more input */
			int offset = (yy_c_buf_p) - (yytext_ptr);
			++(yy_c_buf_p);

			switch ( yy_get_next_buffer(  ) )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					plproxy_yyrestart(plproxy_yyin );

					/*FALLTHROUGH*/

				case EOB_ACT_END_OF_FILE:
					{
					if ( plproxy_yywrap( ) )
						return EOF;

					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					(yy_c_buf_p) = (yytext_ptr) + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) (yy_c_buf_p);	/* cast for 8-bit char's */
	*(yy_c_buf_p) = '\0';	/* preserve plproxy_yytext */
	(yy_hold_char) = *++(yy_c_buf_p);

	if ( c == '\n' )
		   
    plproxy_yylineno++;
;

	return c;
}
#endif	/* ifndef YY_NO_INPUT */

/** Immediately switch to a different input stream.
 * @param input_file A readable stream.
 * 
 * @note This function does not reset the start condition to @c INITIAL .
 */
    void plproxy_yyrestart  (FILE * input_file )
{
    
	if ( ! YY_CURRENT_BUFFER ){
        plproxy_yyensure_buffer_stack ();
		YY_CURRENT_BUFFER_LVALUE =
            plproxy_yy_create_buffer(plproxy_yyin,YY_BUF_SIZE );
	}

	plproxy_yy_init_buffer(YY_CURRENT_BUFFER,input_file );
	plproxy_yy_load_buffer_state( );
}

/** Switch to a different input buffer.
 * @param new_buffer The new input buffer.
 * 
 */
    void plproxy_yy_switch_to_buffer  (YY_BUFFER_STATE  new_buffer )
{
    
	/* TODO. We should be able to replace this entire function body
	 * with
	 *		plproxy_yypop_buffer_state();
	 *		plproxy_yypush_buffer_state(new_buffer);
     */
	plproxy_yyensure_buffer_stack ();
	if ( YY_CURRENT_BUFFER == new_buffer )
		return;

	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	YY_CURRENT_BUFFER_LVALUE = new_buffer;
	plproxy_yy_load_buffer_state( );

	/* We don't actually know whether we did this switch during
	 * EOF (plproxy_yywrap()) processing, but the only time this flag
	 * is looked at is after plproxy_yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	(yy_did_buffer_switch_on_eof) = 1;
}

static void plproxy_yy_load_buffer_state  (void)
{
    	(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
	(yytext_ptr) = (yy_c_buf_p) = YY_CURRENT_BUFFER_LVALUE->yy_buf_pos;
	plproxy_yyin = YY_CURRENT_BUFFER_LVALUE->yy_input_file;
	(yy_hold_char) = *(yy_c_buf_p);
}

/** Allocate and initialize an input buffer state.
 * @param file A readable stream.
 * @param size The character buffer size in bytes. When in doubt, use @c YY_BUF_SIZE.
 * 
 * @return the allocated buffer state.
 */
    YY_BUFFER_STATE plproxy_yy_create_buffer  (FILE * file, int  size )
{
	YY_BUFFER_STATE b;
    
	b = (YY_BUFFER_STATE) plproxy_yyalloc(sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in plproxy_yy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) plproxy_yyalloc(b->yy_buf_size + 2  );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in plproxy_yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	plproxy_yy_init_buffer(b,file );

	return b;
}

/** Destroy the buffer.
 * @param b a buffer created with plproxy_yy_create_buffer()
 * 
 */
    void plproxy_yy_delete_buffer (YY_BUFFER_STATE  b )
{
    
	if ( ! b )
		return;

	if ( b == YY_CURRENT_BUFFER ) /* Not sure if we should pop here. */
		YY_CURRENT_BUFFER_LVALUE = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		plproxy_yyfree((void *) b->yy_ch_buf  );

	plproxy_yyfree((void *) b  );
}

/* Initializes or reinitializes a buffer.
 * This function is sometimes called more than once on the same buffer,
 * such as during a plproxy_yyrestart() or at EOF.
 */
    static void plproxy_yy_init_buffer  (YY_BUFFER_STATE  b, FILE * file )

{
	int oerrno = errno;
    
	plproxy_yy_flush_buffer(b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

    /* If b is the current buffer, then plproxy_yy_init_buffer was _probably_
     * called from plproxy_yyrestart() or through yy_get_next_buffer.
     * In that case, we don't want to reset the lineno or column.
     */
    if (b != YY_CURRENT_BUFFER){
        b->yy_bs_lineno = 1;
        b->yy_bs_column = 0;
    }

        b->yy_is_interactive = 0;
    
	errno = oerrno;
}

/** Discard all buffered characters. On the next scan, YY_INPUT will be called.
 * @param b the buffer state to be flushed, usually @c YY_CURRENT_BUFFER.
 * 
 */
    void plproxy_yy_flush_buffer (YY_BUFFER_STATE  b )
{
    	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == YY_CURRENT_BUFFER )
		plproxy_yy_load_buffer_state( );
}

/** Pushes the new state onto the stack. The new state becomes
 *  the current state. This function will allocate the stack
 *  if necessary.
 *  @param new_buffer The new state.
 *  
 */
void plproxy_yypush_buffer_state (YY_BUFFER_STATE new_buffer )
{
    	if (new_buffer == NULL)
		return;

	plproxy_yyensure_buffer_stack();

	/* This block is copied from plproxy_yy_switch_to_buffer. */
	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	/* Only push if top exists. Otherwise, replace top. */
	if (YY_CURRENT_BUFFER)
		(yy_buffer_stack_top)++;
	YY_CURRENT_BUFFER_LVALUE = new_buffer;

	/* copied from plproxy_yy_switch_to_buffer. */
	plproxy_yy_load_buffer_state( );
	(yy_did_buffer_switch_on_eof) = 1;
}

/** Removes and deletes the top of the stack, if present.
 *  The next element becomes the new top.
 *  
 */
void plproxy_yypop_buffer_state (void)
{
    	if (!YY_CURRENT_BUFFER)
		return;

	plproxy_yy_delete_buffer(YY_CURRENT_BUFFER );
	YY_CURRENT_BUFFER_LVALUE = NULL;
	if ((yy_buffer_stack_top) > 0)
		--(yy_buffer_stack_top);

	if (YY_CURRENT_BUFFER) {
		plproxy_yy_load_buffer_state( );
		(yy_did_buffer_switch_on_eof) = 1;
	}
}

/* Allocates the stack if it does not exist.
 *  Guarantees space for at least one push.
 */
static void plproxy_yyensure_buffer_stack (void)
{
	int num_to_alloc;
    
	if (!(yy_buffer_stack)) {

		/* First allocation is just for 2 elements, since we don't know if this
		 * scanner will even need a stack. We use 2 instead of 1 to avoid an
		 * immediate realloc on the next call.
         */
		num_to_alloc = 1;
		(yy_buffer_stack) = (struct yy_buffer_state**)plproxy_yyalloc
								(num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		
		memset((yy_buffer_stack), 0, num_to_alloc * sizeof(struct yy_buffer_state*));
				
		(yy_buffer_stack_max) = num_to_alloc;
		(yy_buffer_stack_top) = 0;
		return;
	}

	if ((yy_buffer_stack_top) >= ((yy_buffer_stack_max)) - 1){

		/* Increase the buffer to prepare for a possible push. */
		int grow_size = 8 /* arbitrary grow size */;

		num_to_alloc = (yy_buffer_stack_max) + grow_size;
		(yy_buffer_stack) = (struct yy_buffer_state**)plproxy_yyrealloc
								((yy_buffer_stack),
								num_to_alloc * sizeof(struct yy_buffer_state*)
								);

		/* zero only the new slots.*/
		memset((yy_buffer_stack) + (yy_buffer_stack_max), 0, grow_size * sizeof(struct yy_buffer_state*));
		(yy_buffer_stack_max) = num_to_alloc;
	}
}

/** Setup the input buffer state to scan directly from a user-specified character buffer.
 * @param base the character buffer
 * @param size the size in bytes of the character buffer
 * 
 * @return the newly allocated buffer state object. 
 */
YY_BUFFER_STATE plproxy_yy_scan_buffer  (char * base, yy_size_t  size )
{
	YY_BUFFER_STATE b;
    
	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return 0;

	b = (YY_BUFFER_STATE) plproxy_yyalloc(sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in plproxy_yy_scan_buffer()" );

	b->yy_buf_size = size - 2;	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = 0;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	plproxy_yy_switch_to_buffer(b  );

	return b;
}

/** Setup the input buffer state to scan a string. The next call to plproxy_yylex() will
 * scan from a @e copy of @a str.
 * @param str a NUL-terminated string to scan
 * 
 * @return the newly allocated buffer state object.
 * @note If you want to scan bytes that may contain NUL values, then use
 *       plproxy_yy_scan_bytes() instead.
 */
YY_BUFFER_STATE plproxy_yy_scan_string (yyconst char * yystr )
{
    
	return plproxy_yy_scan_bytes(yystr,strlen(yystr) );
}

/** Setup the input buffer state to scan the given bytes. The next call to plproxy_yylex() will
 * scan from a @e copy of @a bytes.
 * @param bytes the byte buffer to scan
 * @param len the number of bytes in the buffer pointed to by @a bytes.
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE plproxy_yy_scan_bytes  (yyconst char * yybytes, int  _yybytes_len )
{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	int i;
    
	/* Get memory for full buffer, including space for trailing EOB's. */
	n = _yybytes_len + 2;
	buf = (char *) plproxy_yyalloc(n  );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in plproxy_yy_scan_bytes()" );

	for ( i = 0; i < _yybytes_len; ++i )
		buf[i] = yybytes[i];

	buf[_yybytes_len] = buf[_yybytes_len+1] = YY_END_OF_BUFFER_CHAR;

	b = plproxy_yy_scan_buffer(buf,n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in plproxy_yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
}

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

static void yy_fatal_error (yyconst char* msg )
{
    	(void) fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
}

/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up plproxy_yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		plproxy_yytext[plproxy_yyleng] = (yy_hold_char); \
		(yy_c_buf_p) = plproxy_yytext + yyless_macro_arg; \
		(yy_hold_char) = *(yy_c_buf_p); \
		*(yy_c_buf_p) = '\0'; \
		plproxy_yyleng = yyless_macro_arg; \
		} \
	while ( 0 )

/* Accessor  methods (get/set functions) to struct members. */

/** Get the current line number.
 * 
 */
int plproxy_yyget_lineno  (void)
{
        
    return plproxy_yylineno;
}

/** Get the input stream.
 * 
 */
FILE *plproxy_yyget_in  (void)
{
        return plproxy_yyin;
}

/** Get the output stream.
 * 
 */
FILE *plproxy_yyget_out  (void)
{
        return plproxy_yyout;
}

/** Get the length of the current token.
 * 
 */
int plproxy_yyget_leng  (void)
{
        return plproxy_yyleng;
}

/** Get the current token.
 * 
 */

char *plproxy_yyget_text  (void)
{
        return plproxy_yytext;
}

/** Set the current line number.
 * @param line_number
 * 
 */
void plproxy_yyset_lineno (int  line_number )
{
    
    plproxy_yylineno = line_number;
}

/** Set the input stream. This does not discard the current
 * input buffer.
 * @param in_str A readable stream.
 * 
 * @see plproxy_yy_switch_to_buffer
 */
void plproxy_yyset_in (FILE *  in_str )
{
        plproxy_yyin = in_str ;
}

void plproxy_yyset_out (FILE *  out_str )
{
        plproxy_yyout = out_str ;
}

int plproxy_yyget_debug  (void)
{
        return plproxy_yy_flex_debug;
}

void plproxy_yyset_debug (int  bdebug )
{
        plproxy_yy_flex_debug = bdebug ;
}

static int yy_init_globals (void)
{
        /* Initialization is the same as for the non-reentrant scanner.
     * This function is called from plproxy_yylex_destroy(), so don't allocate here.
     */

    /* We do not touch plproxy_yylineno unless the option is enabled. */
    plproxy_yylineno =  1;
    
    (yy_buffer_stack) = 0;
    (yy_buffer_stack_top) = 0;
    (yy_buffer_stack_max) = 0;
    (yy_c_buf_p) = (char *) 0;
    (yy_init) = 0;
    (yy_start) = 0;

/* Defined in main.c */
#ifdef YY_STDINIT
    plproxy_yyin = stdin;
    plproxy_yyout = stdout;
#else
    plproxy_yyin = (FILE *) 0;
    plproxy_yyout = (FILE *) 0;
#endif

    /* For future reference: Set errno on error, since we are called by
     * plproxy_yylex_init()
     */
    return 0;
}

/* plproxy_yylex_destroy is for both reentrant and non-reentrant scanners. */
int plproxy_yylex_destroy  (void)
{
    
    /* Pop the buffer stack, destroying each element. */
	while(YY_CURRENT_BUFFER){
		plproxy_yy_delete_buffer(YY_CURRENT_BUFFER  );
		YY_CURRENT_BUFFER_LVALUE = NULL;
		plproxy_yypop_buffer_state();
	}

	/* Destroy the stack itself. */
	plproxy_yyfree((yy_buffer_stack) );
	(yy_buffer_stack) = NULL;

    /* Reset the globals. This is important in a non-reentrant scanner so the next time
     * plproxy_yylex() is called, initialization will occur. */
    yy_init_globals( );

    return 0;
}

/*
 * Internal utility routines.
 */

#ifndef yytext_ptr
static void yy_flex_strncpy (char* s1, yyconst char * s2, int n )
{
	register int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
}
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (yyconst char * s )
{
	register int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
}
#endif

#define YYTABLES_NAME "yytables"

#line 228 "scanner.l"



static char *dlr_token = NULL;

/* remember dollar quote name */
static void dlr_start(const char *txt)
{
	dlr_token = pstrdup(txt);
	if (0) yy_fatal_error("silence 'unused' warning");
}

/* check if matches stored name */
static bool dlr_stop(const char *txt)
{
	bool res =  strcmp(txt, dlr_token) == 0;
	if (res) {
		pfree(dlr_token);
		dlr_token = NULL;
	}
	return res;
}

static const char *unquote(const char *qstr, bool std)
{
	const char *p;
	StringInfoData buf;

	initStringInfo(&buf);
	for (p = qstr + 1; *p; p++) {
		if (*p == '\'') {
			if (*++p == 0)
				break;
			appendStringInfoChar(&buf, *p);
		} else
			appendStringInfoChar(&buf, *p);
	}
	/* leak buf.data */
	return buf.data;
}


